#!/usr/bin/env python
#Author: Andrew Sturtevant
#Description: This is a simply chat server for CS372

#This code was heavily borrowed and influenced by Oregon State University's
#CS372 Lecture 15 Python TCP Server code example

#Basic setup also influence by: https://docs.python.org/2/library/socket.html

import sys
import socket



#Start-Up
def startUp():

	serverPort = int(sys.argv[1])
	HOST = ''
	serverSocket = socket.socket(socket.AF_INET,socket.SOCK_STREAM)
	serverSocket.bind((HOST,serverPort))
	serverSocket.listen(1)

	print "Server ready"
	return serverSocket

def sendMessage(connectionSocket,handle,end):
	message = raw_input(handle)

	if message == end:
		return message

	fullMessage = handle+message
	connectionSocket.send(fullMessage)

	return message
	

	
def receiveMessage(connectionSocket):
	sentence = connectionSocket.recv(512);
	print sentence
	return sentence
		
		
#Driver Code

handle = raw_input("What is your handle?(9 characters or less:")
handle = handle+">"
serverSocket = startUp()

end = "\quit"
while 1:
	connectionSocket, addr = serverSocket.accept()
	message = "start"
	while message != end:
		data = receiveMessage(connectionSocket)
		if not data: 
			print "Client has Disconnected"
			break
		message = sendMessage(connectionSocket,handle,end)

	connectionSocket.close()

