#!/usr/bin/env python
#Author: Andrew Sturtevant
#Description: This is a file transfer client

#Client set-up influenced by: https://pymotw.com/2/socket/tcp.html

import sys
import socket


def initiateContact():

	command = sys.argv[3]
	if command != "-g" and command != "-l":
		print "Invalid Command"
		return 0
	sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	serverName = sys.argv[1]
	connectionPort = int(sys.argv[2])
	server_address = (serverName,connectionPort)
#	print 'connectiong to %s port %s' % server_address
	sock.connect(server_address)

	return sock  



def makeRequest(connectionSocket):

	message = ''
	dataPort = 0
	command = sys.argv[3]

	if command == "-l" and len(sys.argv) == 5:
		dataPort = int(sys.argv[4])
		message = "%s %d" % (command,dataPort)


	elif command == "-g" and len(sys.argv) == 6:
		command = sys.argv[3]
		fileName = sys.argv[4]
		dataPort = int(sys.argv[5])
		message = "%s %d %s" % (command,dataPort,fileName)
	else:
		print "Not the correct # of arguments"

	#Sending message to server to connect to dataport
	
	HOST = ''
	dataSocket = socket.socket(socket.AF_INET,socket.SOCK_STREAM)
	dataSocket.bind((HOST,dataPort))
	connectionSocket.send(message)
	dataSocket.listen(2)
	
	return dataSocket

def receiveData(connectionSocket,dataSocket):

	theSocket, addr = dataSocket.accept()
	if len(sys.argv) == 5:
		hostName = sys.argv[1]
		dataPort = sys.argv[4]
		print ("Receiving directory structure from %s : %s" % (hostName,dataPort))
		direct = theSocket.recv(1024);
		print direct		
	elif len(sys.argv) == 6:
		print "Got here 6"

#Driver Code
#NEEDS: We will want to check to ensure that there are 4 arguments from the
#start.  They will be: Server's Hostname, Connection Port, Command, Data Port
connectionSocket = initiateContact()
if connectionSocket == 0:
	sys.exit()

dataSocket = makeRequest(connectionSocket)
receiveData(connectionSocket,dataSocket)

connectionSocket.close()
dataSocket.close()
